---
- include: single_interface.yml
  when: "{{ enable_veth | bool }}"

- name: Adding Docker apt key
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Adding Docker apt repository
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-trusty main' state=present

- name: Installing dependencies
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python-pip
    - docker-engine
    - python-dev
    - curl
    - python-httplib2

- name: Allow Docker to use an insecure registry
  lineinfile: dest=/etc/default/docker line="DOCKER_OPTS='--insecure-registry {{ registry_vip }}:4000 --registry-mirror=http://{{ registry_vip }}:4000'"

- name: Restart Docker
  service: name=docker state=restarted

- name: Mount /run
  command: mount --make-shared /run

- name: Install docker-py
  pip: name=docker-py
