---
- name: Install common dependencies
  hosts: all
  roles:
    - { role: common,
        tags: ['common'] }

- name: Configure the Docker registry
  hosts: disco/registry
  roles:
    - { role: registry,
        tags: ['registry'] }

- name: Configure the influx database
  hosts: disco/influx
  roles:
    - { role: influx,
        tags: ['influx'],
        when: enable_monitoring | bool }


- name: Install monitoring agent
  hosts: all
  roles:
    - { role: cadvisor,
        tags: ['cadvisor'],
        when: enable_monitoring | bool }
    - { role: collectd,
        tags: ['collectd'],
        when: enable_monitoring | bool }

- name: Configure grafana
  hosts: disco/grafana
  roles:
    - { role: grafana,
        tags: ['grafana'],
        when: enable_monitoring | bool }

- name: Configure Rally
  hosts: disco/rally
  vars:
    os_env:
      OS_PROJECT_DOMAIN_ID: default
      OS_PROJECT_DOMAIN_NAME: default
      OS_USER_DOMAIN_ID: Default
      OS_USER_DOMAIN_NAME: Default
      OS_PROJECT_NAME: admin
      OS_TENANT_NAME: admin
      OS_USERNAME: admin
      OS_PASSWORD: demo
      OS_AUTH_URL: "http://{{ vip }}:5000/v3"
      OS_IDENTITY_API_VERSION: 3
      OS_REGION_NAME: "RegionOne"
  roles:
    - { role: rally,
        tags: ['rally'],
        when: enable_rally | bool }

