cadvisor:
  housekeeping_interval: 5s

g5k_role: unknown

enable_monitoring: true
enable_rally: true

# will be copied on the rally host to launch scenarios
rally_scenarios_dir: "{{ playbook_dir }}/../rally/"
rally_scenarios_list: "all-scenarios.txt.sample"
rally_times: 1
rally_concurrency: 1

backup_dir: "{{ playbook_dir }}/../current"

# list of available patchs
# to enable one patch copy past its description
# to your local config file and enable it
patches:
  - name: patch galera.cnf.j2
    src: galera.cnf.j2
    dst: kolla/ansible/roles/mariadb/templates/galera.cnf.j2
    enabled: "no"
  - name: patch wsgi-keystone.conf.j2
    src: wsgi-keystone.conf.j2
    dst: kolla/ansible/roles/keystone/templates/wsgi-keystone.conf.j2
    enabled: "no"
